### ISSUE TITLE
Does not remember size of settings panel

### ISSUE THREAD

**Issue by kdato** [mbert/etheme-blingbling-e20#24]
Hi,

I don't get the following issue with the default theme or with rElighted.

Blingbling does not remember the size of Enlightenment's Settings Panel. In there, under "Settings > Dialog ", I have "Remember size and position of dialgs" on. However, every time I access the Settings Panel, I increase the panel size so that everything is in view -- the panel fills almost all of my 28 inch screen. However, next time I access settings, the panel reverts to a small window.

I'm on Slackware 15.0 with Xorg, and have had the same issue playing with Manjaro-21.2.1 with Xorg.

Any thoughts? Am I missing something?

Thanks,
kdato

**Comment by mbert** [comment]
No idea to be honest. I am not familiar enough with how it works. Maybe @thewaiter knows?

**Comment by kdato** [comment]
Thanks, I'll try him.

**Comment by thewaiter** [comment]
Hi. Very interesting. OK, I did some investigation. I have found somethig related in dialog.edc  file
description {
	    state:    "default" 0.0;
	    min:      200 138;
	    max:      200 138;
I will get rid these limits and commit. Try to build it and check

Stefan

**Comment by mbert** [comment]
Thank you, PR received, I'll try to look into this ASAP (should be closed by the weekend).

**Comment by mbert** [comment]
> Thank you, PR received, I'll try to look into this ASAP (should be closed by the weekend).

should be closed bz the **end of the weekend**, unfortunately things are a bit rough these days.

**Comment by thewaiter** [comment]
NP, kdato use can use my repo and compile the theme for testing purposes

**Comment by mbert** [comment]
> NP, kdato use can use my repo and compile the theme for testing purposes

A bit quicker than I thought, I have quickly integrated your changes, little testing, made a release. @kdato you may have a go and check.

**Comment by kdato** [comment]
Hi both, many thanks for this. I'll try and get back.
